#!/usr/bin/env sh
#
# zsh 安装与配置。
#
# shellcheck shell=sh

MODULE_DESC="zsh + config fragments (starship-ready)"
MODULE_PLATFORMS="macos linux"
MODULE_TAGS="core shell"

install() {
    # ------------------------------------------------------------ 安装 zsh
    if ! dot_pkg_installed zsh; then
        dot_info 'zsh not found; installing'
        dot_pkg_install zsh || return 1
    else
        dot_skip 'zsh already installed'
    fi

    # ------------------------------------------------------------ 链接配置
    dot_link "$DOT_CONFIG_DIR/zsh/zshrc" "$HOME/.zshrc" || return 1

    # 片段目录整体链接，新增片段无需重跑安装
    dot_link "$DOT_CONFIG_DIR/zsh/zshrc.d" "$HOME/.zshrc.d" || return 1

    # DOTFILES 需要在 zshrc 里解析出仓库位置。zshrc 自己会从符号链接
    # 反查，但显式写一份到 zshenv 更稳（覆盖非交互式 shell 的场景）。
    _dot_zshenv="$HOME/.zshenv"
    if [ ! -e "$_dot_zshenv" ] || grep -q 'DOTFILES=' "$_dot_zshenv" 2>/dev/null; then
        printf '# generated by dotfiles bootstrap; edit config/zsh/ instead\nexport DOTFILES=%s\n' \
            "$DOT_ROOT" | dot_write "$_dot_zshenv" || return 1
    else
        dot_tip "$_dot_zshenv exists and does not set DOTFILES; leaving it alone"
    fi

    # ------------------------------------------------------------ 默认 shell
    _dot_set_default_shell
}

# 把 zsh 设为默认 shell。三条约束：
#   - 已是 zsh 则跳过
#   - headless（SSH/CI/容器）下不改 —— 会话中途换 shell 风险高且无收益
#   - 需要用户确认 —— 这是对账户的持久修改
_dot_set_default_shell() {
    _dot_zsh_path=$(command -v zsh 2>/dev/null)
    [ -n "$_dot_zsh_path" ] || {
        dot_tip 'zsh not on PATH yet; skipping default-shell change'
        return 0
    }

    case "${SHELL:-}" in
        */zsh)
            dot_skip 'zsh is already the default shell'
            return 0
            ;;
    esac

    if [ "$DOT_HEADLESS" = 1 ]; then
        dot_skip 'headless environment; not changing the default shell'
        dot_tip "run 'chsh -s $_dot_zsh_path' yourself when on an interactive machine"
        return 0
    fi

    if dot_is_dry_run; then
        dot_info "[dry-run] would ask to change the default shell to $_dot_zsh_path"
        return 0
    fi

    dot_prompt "Change your default shell to $_dot_zsh_path? [y/N]"
    read -r _dot_answer
    case "$_dot_answer" in
        y | Y | yes | YES)
            # /etc/shells 里没有的 shell 无法被 chsh 接受
            if [ -w /etc/shells ] || grep -qx "$_dot_zsh_path" /etc/shells 2>/dev/null; then
                :
            else
                dot_tip "$_dot_zsh_path is not listed in /etc/shells; chsh may refuse it"
            fi
            if chsh -s "$_dot_zsh_path"; then
                dot_success "default shell changed to $_dot_zsh_path (takes effect on next login)"
            else
                dot_error 'chsh failed; change your shell manually'
                return 1
            fi
            ;;
        *)
            dot_skip 'leaving the default shell unchanged'
            dot_tip "run 'chsh -s $_dot_zsh_path' later if you change your mind"
            ;;
    esac
}
